name: Python environment information
description: "Print various Python environment information including installed packages"
outputs:
  output:
    description: "The full informational output"
    value: ${{ steps.the_run.outputs.output }}
runs:
  using: "composite"
  steps:
    - id: the_run
      run: |
        python info.py
