name: Python environment information
description: "Print various Python environment information including installed packages"
inputs:
  output-path:
    description: "A file path to write the information to."
    required: False
    default: ""
outputs:
  output:
    description: "The full informational output"
    value: ${{ steps.the_run.outputs.output }}
runs:
  using: "composite"
  steps:
    - shell: python
      id: the_run
      run: $/info.py
      env:
        ACTION_FILE_PATH: ${{ inputs.output-path }}
