name: CI

on:
  push:
    branches: [ main ]
    tags:
      - "*"
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: ${{ matrix.task.name}} - ${{ matrix.python.name }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python:
          - name: CPython 2.7
            action: 2.7
          - name: CPython 3.9
            action: 3.9
          - name: PyPy 2
            action: pypy2
          - name: PyPy 3
            action: pypy3

    steps:
    - uses: actions/checkout@v2

    - name: Set up ${{ matrix.python.name }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python.action }}

    - name: Run the action
      uses: ./
      id: the_action

    - name: Test
      run: echo ${{ job.the_action.outputs.output }}

  all:
    name: All
    runs-on: ubuntu-latest
    needs:
      - ci
    steps:
      - name: This
        shell: python
        run: |
          import this
