name: CI

on:
  push:
    branches: [ main ]
    tags:
      - "*"
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: ${{ matrix.task.name}} - ${{ matrix.python.name }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python:
          - name: CPython 2.7
            action: 2.7
          - name: CPython 3.9
            action: 3.9
          - name: PyPy 2
            action: pypy2
          - name: PyPy 3
            action: pypy3

    steps:
    - uses: actions/checkout@v2

    - name: Set up ${{ matrix.python.name }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python.action }}

    - name: Run the action
      uses: ./
      id: the_action
      with:
        output-path: output_pre.log

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.task.name}} - ${{ matrix.python.name }}
        path: output_pre.log

    - name: Test
      shell: bash
      run: |
        python test.py --path output_pre.log

    - name: Install attrs
      shell: bash
      run: |
        python -m pip install attrs==20.3.0

    - name: Run the action with attrs installed
      uses: ./
      id: the_action
      with:
        output-path: output_post.log

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.task.name}} - ${{ matrix.python.name }}
        path: output_post.log

    - name: Test
      shell: bash
      run: |
        python test.py --path output_post.log --package attrs 20.3.0

  all:
    name: All
    runs-on: ubuntu-latest
    needs:
      - ci
    steps:
      - name: This
        shell: python
        run: |
          import this
